[package]
name = "batch_renderer_2_d"
version = "0.1.0"
authors = ["Rosca Alex <roscaalex19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.35.0"
gl = "0.14.0"
rand = "0.7.3"
image = "0.22.5"